"""add_option_symbol_to_positions

Revision ID: 1c3159917f07
Revises: 015e4a41dc9e
Create Date: 2026-04-23 14:13:55.520185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3159917f07'
down_revision: Union[str, Sequence[str], None] = '015e4a41dc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('option_symbol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'option_symbol')
    # ### end Alembic commands ###
