"""Exit shadow mode — watch alternative exit rules on live trades, act on none.

OBSERVATION ONLY. Nothing in this module places, cancels or changes an order,
writes to the database, or influences any exit decision. The live exit rules in
`signal_generator.check_exit_signal` run exactly as before; this module is told
what price the engine priced the held contract at on each tick, and records when
each ALTERNATIVE rule *would* have sold.

WHY
---
docs/dynamic-exits-math.md §7 replayed 28 real round trips under alternative exit
rules. None of the profit-side rules beat the live rule like-for-like (an apparent
+$45 for dynamic TP + trail was a look-ahead bug in the replay, caught by running
this module over the same trades). The structure stop added 2026-09-17 did beat it,
by +$31, but only by exiting three losing trades earlier, most of it one trade.
Every one of these is a hypothesis generated by the trades it was measured on. The
honest next step is evidence from trades the analysis has not seen, gathered
without risking an exit. Owner chose this over building selectable exit modes.

RULES WATCHED — same definitions as scripts/dynamic_exits_review.py, so live
shadow results and the offline replay can be compared directly:

  keep70        trail arms at +arm%, sells if price <= entry + 0.70 * (peak - entry)
  keep50        same with 0.50
  vol_trail     trail arms at +arm%, sells if price <= peak - 0.5 * delta * sigma10
  dyn_tp        sells if price >= entry + 2 * delta * sigma30 (fixed at entry)
  dyn_tp_trail  dyn_tp's target, plus the live trail (give back trail% of peak)
  structure     STRUCTURE STOP (added 2026-09-17), plus the live trail. The stop follows
                swing points of the UNDERLYING's 1-minute bars: a bar whose low (calls) /
                high (puts) is beyond the 2 bars on each side, confirmed once those 2 later
                bars close, pivot at or after the entry minute. Stop = swing low − 0.25 ×
                sigma10 (puts: swing high + it), moved only in the trade's favour, fired when
                a completed 1-minute bar CLOSES beyond it. docs/dynamic-exits-math.md §7.

                The bars' highs and lows come from note_underlying(), fed the engine's ~1/s
                underlying price. The offline replay builds them from every recorded print,
                so a live high or low can be a few cents less extreme than the replay's.

Every rule shares the strategy's own stop loss % (as the floor), arm % and trail %,
so only the rule being tested differs from what the engine actually does.

sigma10 / sigma30 = typical 10 / 30-minute move of the UNDERLYING, from the
engine's own 1-minute closes (SignalGenerator.price_history): stdev of the last
30 one-minute changes, scaled by sqrt(minutes). Causal — only bars the engine
already had.

WHAT A RESULT MEANS
-------------------
A rule that would sell BEFORE the real exit is fully measured: time, price, P&L.
A rule still holding when the engine really sells is recorded as `open` with the
price and peak at that moment — its outcome is unknown, because the contract
usually stops being streamed after the sale. That is the same "unresolved"
category the offline replay reports; never count it as flat.

Snapshots taken more than LATE_SNAPSHOT_S after the position opened (a restart
mid-trade) are flagged `late`: delta, sigma30 and the dynamic target then describe
the moment shadow first saw the position, not the entry.

OUTPUT
------
  * one INFO line per rule, the first time it would sell
  * one INFO summary line when the engine really closes the position
  * one JSONL record per closed position in logs/livetest-<date>/exit_shadow-*.jsonl
    (only when LIVE_TEST_LOGGING is on, like every other session log)

State is module-level, not per executor: StrategyExecutor instances are re-created
in-process, and per-instance state would silently reset in the middle of a trade.
It does not survive a process restart — the next observation starts a `late`
snapshot instead.
"""
import logging
import math
import re
import statistics
import threading
from datetime import datetime, timedelta
from typing import Dict, Iterable, Optional

logger = logging.getLogger(__name__)

ENABLED = True
LATE_SNAPSHOT_S = 120
DEFAULT_DELTA = 0.70          # only when no delta for the held contract is known
RULES = ("keep70", "keep50", "vol_trail", "dyn_tp", "dyn_tp_trail", "structure")
STRUCT_PIVOT = 2          # bars each side of a swing point
STRUCT_BUFFER = 0.25      # x sigma10 beyond the swing
MAX_BARS = 240            # per underlying; ~4 hours of 1-minute bars

_LOCK = threading.Lock()
_STATE: Dict[int, dict] = {}
# { underlying: { minute (naive UTC, second=0): [open, high, low, close] } }
_BARS: Dict[str, dict] = {}
_warned = set()


def _warn_once(key: str, msg: str) -> None:
    if key not in _warned:
        _warned.add(key)
        logger.warning(msg)


def sigma(closes: Iterable[float], minutes: int, lookback: int = 30) -> Optional[float]:
    """Typical `minutes`-minute move from the last `lookback` 1-minute closes."""
    c = list(closes)[-(lookback + 1):]
    diffs = [c[i] - c[i - 1] for i in range(1, len(c))]
    if len(diffs) < 20:
        return None
    sd = statistics.pstdev(diffs)
    return sd * math.sqrt(minutes) if sd > 0 else None


def _pct(params: dict, *keys, default: float) -> float:
    for k in keys:
        v = (params or {}).get(k)
        if v not in (None, "", False):
            try:
                return float(v)
            except (TypeError, ValueError):
                pass
    return default


def note_underlying(symbol: str, price: float, now: Optional[datetime] = None) -> None:
    """Fold one underlying price into its 1-minute OHLC bar. Never raises.

    Called on EVERY evaluation tick, flat or holding, so the swing points before a
    trade exist when the trade opens (a pivot needs two bars on each side).
    """
    if not ENABLED:
        return
    try:
        if not symbol or price is None or float(price) <= 0:
            return
        px = float(price)
        minute = (now or datetime.utcnow()).replace(second=0, microsecond=0)
        with _LOCK:
            bars = _BARS.setdefault(symbol, {})
            bar = bars.get(minute)
            if bar is None:
                bars[minute] = [px, px, px, px]
                if len(bars) > MAX_BARS:
                    for k in sorted(bars)[:len(bars) - MAX_BARS]:
                        del bars[k]
            else:
                bar[1] = max(bar[1], px)
                bar[2] = min(bar[2], px)
                bar[3] = px
    except Exception as exc:
        _warn_once("note_underlying", f"exit shadow: note_underlying failed, bars skipped ({exc!r})")


def observe(position, price: float, closes: Iterable[float], params: dict,
            delta: Optional[float] = None, now: Optional[datetime] = None,
            underlying: Optional[str] = None) -> None:
    """Record one priced tick for an open position. Never raises."""
    if not ENABLED:
        return
    try:
        _observe(position, price, closes, params, delta, now or datetime.utcnow(), underlying)
    except Exception as exc:  # observation must never reach the exit path
        _warn_once("observe", f"exit shadow: observe failed, shadow skipped ({exc!r})")


def _observe(position, price, closes, params, delta, now, underlying=None):
    if price is None or price <= 0 or position is None or position.id is None:
        return
    entry = float(position.avg_entry_price)
    if entry <= 0:
        return
    with _LOCK:
        st = _STATE.get(position.id)
        if st is None:
            closes = list(closes or [])
            d = float(delta) if delta else None
            s30 = sigma(closes, 30)
            opened = getattr(position, "opened_at", None)
            late = bool(opened and (now - opened).total_seconds() > LATE_SNAPSHOT_S)
            st = dict(
                option_symbol=position.option_symbol, entry=entry,
                qty=int(position.qty or 0), opened_at=opened, first_seen=now, late=late,
                delta=d if d else DEFAULT_DELTA, delta_known=bool(d),
                sigma30=s30,
                target=(entry + 2 * (d if d else DEFAULT_DELTA) * s30) if s30 else None,
                stop_pct=_pct(params, "stop_loss_pct", "stop_loss_percentage", default=15.0),
                arm_pct=_pct(params, "trailing_stop_activation", default=15.0),
                trail_pct=_pct(params, "trailing_stop_distance", default=10.0),
                peak=price, armed=False, last=price, exits={},
                underlying=underlying,
                is_call=_is_call(position.option_symbol),
                entry_minute=((opened or now).replace(second=0, microsecond=0)),
                struct_stop=None, struct_done=None, struct_moves=0,
            )
            _STATE[position.id] = st
        st["last"] = price
        st["peak"] = max(st["peak"], price)
        closes = list(closes or [])
        _structure_step(st, price, closes, now)
        st["armed"] = st["armed"] or st["peak"] >= entry * (1 + st["arm_pct"] / 100) - 1e-9
        if price <= entry * (1 - st["stop_pct"] / 100):
            for rule in RULES:
                _record(st, rule, price, now, "stop")
            return
        s10 = sigma(closes, 10)
        peak, armed, tgt = st["peak"], st["armed"], st["target"]
        if armed and price <= peak * (1 - st["trail_pct"] / 100):
            _record(st, "structure", price, now, "trail")
        checks = {
            "keep70": armed and price <= entry + 0.70 * (peak - entry),
            "keep50": armed and price <= entry + 0.50 * (peak - entry),
            "vol_trail": armed and s10 is not None and price <= peak - 0.5 * st["delta"] * s10,
            "dyn_tp": tgt is not None and price >= tgt,
        }
        if tgt is not None and price >= tgt:
            checks["dyn_tp_trail"] = "target"
        elif armed and price <= peak * (1 - st["trail_pct"] / 100):
            checks["dyn_tp_trail"] = "trail"
        for rule, hit in checks.items():
            if hit:
                reason = hit if isinstance(hit, str) else ("target" if rule == "dyn_tp" else "trail")
                _record(st, rule, price, now, reason)


def _is_call(option_symbol) -> Optional[bool]:
    m = re.search(r"\d{6}([CP])", option_symbol or "")
    return None if m is None else m.group(1) == "C"


def _structure_step(st, price, closes, now):
    """Process underlying minutes completed since the last tick: fire, then find swings."""
    if "structure" in st["exits"] or st["is_call"] is None or not st["underlying"]:
        return
    bars = _BARS.get(st["underlying"]) or {}
    keys = sorted(bars)
    cur = now.replace(second=0, microsecond=0)
    fresh = [k for k in keys if k < cur and k >= st["entry_minute"]
             and (st["struct_done"] is None or k > st["struct_done"])]
    if not fresh:
        return
    idx = {k: i for i, k in enumerate(keys)}
    is_call = st["is_call"]
    for m in fresh:
        st["struct_done"] = m
        close = bars[m][3]
        stop = st["struct_stop"]
        if stop is not None and ((is_call and close < stop) or (not is_call and close > stop)):
            _record(st, "structure", price, now, "structure")
            return
        i = idx[m]
        if i < 2 * STRUCT_PIVOT:
            continue
        p = keys[i - STRUCT_PIVOT]
        if p < st["entry_minute"]:
            continue
        around = [keys[j] for j in range(i - 2 * STRUCT_PIVOT, i + 1) if j != i - STRUCT_PIVOT]
        if is_call:
            pivot = bars[p][2]
            swing = all(pivot < bars[k][2] for k in around)
        else:
            pivot = bars[p][1]
            swing = all(pivot > bars[k][1] for k in around)
        if not swing:
            continue
        s10 = sigma(closes, 10) or 0.0
        level = pivot - STRUCT_BUFFER * s10 if is_call else pivot + STRUCT_BUFFER * s10
        new = level if stop is None else (max(stop, level) if is_call else min(stop, level))
        if new != stop:
            st["struct_moves"] += 1
        st["struct_stop"] = new


def _record(st, rule, price, now, reason):
    if rule in st["exits"]:
        return
    pnl_pct = (price - st["entry"]) / st["entry"] * 100
    st["exits"][rule] = dict(price=price, at=now, reason=reason, pnl_pct=round(pnl_pct, 2),
                             pnl_usd=round((price - st["entry"]) * 100 * st["qty"], 2))
    logger.info(
        f"SHADOW EXIT {rule}: {st['option_symbol']} would sell ${price:.2f} "
        f"({pnl_pct:+.1f}%, {reason}) — real position still open"
    )


def on_exit(position, real_price: Optional[float], reason: str,
            now: Optional[datetime] = None) -> Optional[dict]:
    """The engine really closed `position`. Summarise, emit, forget. Never raises."""
    if not ENABLED:
        return None
    try:
        return _on_exit(position, real_price, reason, now or datetime.utcnow())
    except Exception as exc:
        _warn_once("on_exit", f"exit shadow: summary failed ({exc!r})")
        return None


def _on_exit(position, real_price, reason, now):
    with _LOCK:
        st = _STATE.pop(getattr(position, "id", None), None)
        # Positions closed somewhere shadow never hears about (reconcile, manual
        # close) would otherwise sit here forever.
        for pid in [p for p, s in _STATE.items() if now - s["first_seen"] > timedelta(days=1)]:
            _STATE.pop(pid, None)
    if st is None:
        return None
    entry, qty = st["entry"], st["qty"]
    real = None
    if real_price:
        real = dict(price=real_price, reason=reason,
                    pnl_pct=round((real_price - entry) / entry * 100, 2),
                    pnl_usd=round((real_price - entry) * 100 * qty, 2))
    rules = {}
    parts = []
    for rule in RULES:
        ex = st["exits"].get(rule)
        if ex:
            rules[rule] = dict(status="sold", **ex)
            parts.append(f"{rule} ${ex['price']:.2f} ({ex['pnl_usd']:+.0f})")
        else:
            rules[rule] = dict(status="open", last=st["last"], peak=st["peak"])
            parts.append(f"{rule} still open")
    record = dict(
        option_symbol=st["option_symbol"], qty=qty, entry=entry,
        opened_at=st["opened_at"], first_seen=st["first_seen"], closed_at=now, late=st["late"],
        delta=st["delta"], delta_known=st["delta_known"], sigma30=st["sigma30"],
        target=st["target"], struct_stop=st["struct_stop"], struct_moves=st["struct_moves"],
        underlying=st["underlying"], stop_pct=st["stop_pct"], arm_pct=st["arm_pct"],
        trail_pct=st["trail_pct"], peak=st["peak"], armed=st["armed"],
        real=real, rules=rules,
    )
    real_txt = (f"${real['price']:.2f} ({real['pnl_usd']:+.0f})" if real else "unknown fill")
    logger.info(
        f"SHADOW SUMMARY {st['option_symbol']}: real {real_txt} [{reason}] | "
        + " | ".join(parts)
        + (" | LATE snapshot" if st["late"] else "")
    )
    try:
        from live_test.logging_setup import is_enabled, get_jsonl_logger
        if is_enabled():
            get_jsonl_logger("exit_shadow").emit(record)
    except Exception as exc:
        _warn_once("jsonl", f"exit shadow: JSONL emit failed ({exc!r})")
    return record


def _reset_for_tests() -> None:
    with _LOCK:
        _STATE.clear()
        _BARS.clear()
    _warned.clear()
